language: python
python:
- '3.6'
script:
- touch foo
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "agAgXszFwcs6PMO5zcB4riWd7pLmZbnv24+S+sk0qBiTd9s4yTf3V8ycuxRT/udhYrdcqZjHGM6VAw8BYJZW3P+n1oj8IrKBR9dcf/VzadUT2u/Fv+lVd6aywlKdHo5xXUBduDAEKLVpkTNNzz100N+Wep22Zes7WyqsMQ2lhiBm6gfZHHA0l2vOfFzoBq/gzreLJEnDI/HmTQd/Gi3ZMFCrY38zRYsL9/pxARttkLEUA9hZV2+tqDdggSjfWPK15oy4Nw7us/OJ2f+n9QpAdmJL9Up9VOXqs7fINSLs8A4P9AM+QkOFKa/ARlXCWOE/zls5ZdfGE4rRD4FlDxlrrhapWRrgosMukOadCByfrpITY/uG05jrJe5LYGb4UVOxInz0cvLQtqMkD48bFI/TVPBuP3271OhszMQnFgaKDMuysS+fD6PUHVXu1NEXSkGhS46k3NweWGwftKFwEzD2tRNF2FlPxEn3js57ruDJtUL7//0UKhcUlHpGu+vEatEg2JTDJthjDxSAunzVzUEtI4fGowKIRD9sTodPJDtZebftlOoZr3Z5D7ySko8RCWOxWarAedFki+Uwj4Ii5rDAQQG5/iZM8rqy6Qo6yYcsqJ+c7Ir8cWhyxVH5fGjy0c/TELiOt7e6Mqd09WW1ZZAO5/3lRIAwHtR6NDKecaJ9DZs="
  password: 
  on:
    tags: true
    branch: master
