{% set data = load_setup_py_data() %}

package:
  name: peleffy
  version: {{ data.get('version') }}

source:
  path: ../../

build:
  script: python -m pip install . --no-deps
  number: 0
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python >=3.12
    - numpy
    - ipython
    - matplotlib
    - pytest
    - networkx
    - rdkit >=2025.03.6
    - ambertools
    - openff-toolkit ==0.18.0
    - openff-forcefields ==2026.01.0
    - openff-nagl ==0.5.4

about:
  home: https://github.com/martimunicoy/peleffy
  license: MIT
