{% set data = load_setup_py_data() %}

package:
  name: peleffy
  version: {{ data.get('version') }}

source:
  path: ../../

build:
  script: python -m pip install . --no-deps
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - matplotlib
    - pytest
    - networkx
    - rdkit
    - ambertools
    - openff-toolkit==0.9.2

about:
  home: https://github.com/martimunicoy/peleffy
  license: MIT
