name: Conda deployment

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macOS-latest]
        #python-version: [3.7, 3.8, 3.9]
        python-version: [3.8]
        os: [ubuntu-latest]
    name: Python ${{ matrix.python-version }} at ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        name: Conda setup
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: standard
          auto-activate-base: false
      - name: Install conda-build
        run: conda install conda-build
      - name: Install anaconda-client
        run: conda install anaconda-client
      - name: Configurate conda-build
        run: conda config --set anaconda_upload yes
      - name: Configurate conda-client from anaconda
        run: anaconda login --hostname peleffy14host${{ matrix.python-version }}${{ matrix.os }} --username ${{ secrets.ANACONDA_USER }} --password ${{ secrets.ANACONDA_PASSWD }}
      - name: Deploy package to conda
        run: conda build 'devtools/conda'
      - name: Logout from anaconda
        run: anaconda logout

      #- name: Setup conda
      #  uses: s-weigand/setup-conda@v1
      #  with:
      #    update-conda: true
      #    python-version: ${{ matrix.python-version }}
      #    conda-channels: anaconda, conda-forge
      #- name: Fix problem with urllib
      #  run: |
      #    pip uninstall urllib3
      #    pip install --upgrade urllib3
      #- name: Install conda-build
      #  run: conda install conda-build
      #- name: Install anaconda-client
      #  run: conda install anaconda-client
      #- name: Configurate conda-build
      #  run: conda config --set anaconda_upload yes
      #- name: Configurate conda-client from anaconda
      #  run: anaconda login --hostname peleffy14host${{ matrix.python-version }}${{ matrix.os }} --username ${{ secrets.ANACONDA_USER }} --password ${{ secrets.ANACONDA_PASSWD }}
      #- name: Deploy package to conda
      #  run: conda build 'devtools/conda'
      #- name: Logout from anaconda
      #  run: anaconda logout
