name: Conda deployment

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest, macOS-latest]
        #python-version: [3.6, 3.7]
        os: [ubuntu-latest]
        python-version: [3.6]
    name: Python ${{ matrix.python-version }} at ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - run: conda install conda-build
      - run: conda build -c rdkit -c omnia 'devtools/conda'
