name: Build documentation

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  documentation_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.7
          conda-channels: anaconda, omnia, conda-forge, martimunicoy

      - name: Install doc dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --no-deps -v .
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

      - name: Build sphinx documentation
        shell: bash
        run: |
          cd docs/
          make github
        
      # https://github.com/peaceiris/actions-gh-pages
      - name: Deploy documentation
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
            publish_branch: gh-pages
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: docs/html/
            user_name: 'Martí Municoy'
            user_email: 'martimunicoy@gmail.com'
