name: Build documentation

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  documentation_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi

    - name: Build sphinx documentation
      shell: bash -l {0}
      run: |
        cd docs/
        make github
        
    - name: Build sphinx documentation (again)
      shell: bash -l {0}
      run: |
        make github
        
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy documentation
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/html/
          user_name: 'Martí Municoy'
          user_email: 'martimunicoy@gmail.com'
