name: PyPI deployment

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deployment
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

