name: PyPI deployment

on: [release]

jobs:
  build:
    name: Deployment
    steps:
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.3.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}

